# Generated by Django 4.0.5 on 2022-06-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('conducted', models.CharField(max_length=200)),
                ('date_started', models.CharField(max_length=200)),
                ('date_ended', models.CharField(max_length=200)),
                ('time_duration', models.CharField(max_length=200)),
                ('seminar_type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Seminar',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('conducted', models.CharField(max_length=200)),
                ('date_started', models.CharField(max_length=200)),
                ('date_ended', models.CharField(max_length=200)),
                ('time_duration', models.CharField(max_length=200)),
                ('skill_type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('conducted', models.CharField(max_length=200)),
                ('date_started', models.CharField(max_length=200)),
                ('date_ended', models.CharField(max_length=200)),
                ('time_duration', models.CharField(max_length=200)),
                ('seminar_type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Workshop',
            },
        ),
    ]
