# Generated by Django 4.0.5 on 2022-06-20 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('address', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('conducted', models.CharField(max_length=200)),
                ('date_started', models.CharField(max_length=200)),
                ('date_ended', models.CharField(max_length=200)),
                ('time_duration', models.CharField(max_length=200)),
                ('seminar_type', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Workshop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Workshop',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('conducted', models.CharField(max_length=200)),
                ('date_started', models.CharField(max_length=200)),
                ('date_ended', models.CharField(max_length=200)),
                ('time_duration', models.CharField(max_length=200)),
                ('skill_type', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('user', models.OneToOneField(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Skill', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('conducted', models.CharField(max_length=200)),
                ('date_started', models.CharField(max_length=200)),
                ('date_ended', models.CharField(max_length=200)),
                ('time_duration', models.CharField(max_length=200)),
                ('seminar_type', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seminar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seminar',
            },
        ),
    ]
